# Generated by Django 5.0.1 on 2026-03-11 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarbonEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("transport", "Transport"),
                            ("electricity", "Electricity"),
                            ("food", "Food"),
                            ("shopping", "Shopping"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "emission_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="CO2 in kg", max_digits=10
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carbon_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Carbon Entries",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
